### PR TITLE
Refractor: Removed some useless files and code.

### PR DESCRIPTION
**Pull request by nikhilmaske-2001**
Refractor: Removed some useless files and code.

Testing: I have tested and everything works fine after this changes.

### CODE REVIEW

**Comment by nikhilmaske-2001** [comment]
By mistake I have created this pull request from master. I will fix it.
I have a question, Do I need to remove `package-lock.json` file from this PR?

**Comment by Gautam-Arora24** [comment]
@nikhilmaske-2001 I think we shouldn't remove `package-lock.json` file. 
Found this in official docs ->
`
package-lock.json is automatically generated for any operations where npm modifies either the node_modules tree, or package.json. It describes the exact tree that was generated, such that subsequent installs are able to generate identical trees, regardless of intermediate dependency updates.
`

**Comment by Gautam-Arora24** [comment]
@nikhilmaske-2001 Can we create an issue for this and then create a PR for the same? This way it will help us track the files changed, later down the line :)

**Comment by nikhilmaske-2001** [comment]
I deleted that `package-lock.json` files from my local machine and still I am not facing any issue. Maybe it is better not to merge my `package-lock.json` into the upstream repo as the upstream already have one `package-lock.json`
(PS: Here upstream for me means your main repo)

**Pull request closed without merging**
